version: "3.1"

services:
  db:
    image: mysql:lts
    restart: always
    privileged: true
    ports:
      - "3306:3306"
    volumes:
      - ./sql/easychat.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: easychat
    networks:
      - easychat
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - easychat
  minio:
    image: minio/minio
    command: server --console-address ":9001" ./data
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: miniopassword
    networks:
      - easychat
  easychat:
    build: .
    ports:
      - "8080:8080"
    networks:
      - easychat
    depends_on:
      - db
      - redis
      - minio
networks:
  easychat:
    driver: bridge