spring:
  config:
    import: classpath:application-my.yaml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easychat
    username: easychat
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379