spring:
logging:
  level:
    top.th1nk.easychat: debug
  config:
    import: classpath:application-my.yaml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easychat
    username: easychat
    password: 123456
    druid:
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico,*.html,*.json
      filter:
        stat:
          enabled: true # 开启SQL监控
      stat-view-servlet:
        enabled: true # 开启druid监控面板
        url-pattern: /druid/*
  data:
    redis:
      host: localhost
      port: 6379
springdoc:
  # 开启swagger-ui
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
easy-chat:
  security:
    permit-all-urls:
      - /user/login
      - /user/register
      - /user/verify-email
      - /user/email/register
      - /user/email/login
      - /upload/${easy-chat.user.avatar-dir}/**
      - /upload/${easy-chat.chat.file-dir}/**
      - /upload/${easy-chat.group.avatar-dir}/**
      - /chat/ws/**
      # 开发时配置
      - /swagger-ui/**
      - /v3/api-docs/**
      - /druid/**